galaxy reporting task

diff --git a/galaxy-pasteur/roles/galaxy/templates/galaxy-reporting b/galaxy-pasteur/roles/galaxy/templates/galaxy-reporting
--- a/galaxy-pasteur/roles/galaxy/templates/galaxy-reporting
+++ b/galaxy-pasteur/roles/galaxy/templates/galaxy-reporting
@@ -1,86 +1,106 @@
 #!/bin/bash
+#{{ ansible_managed }}
 #
-# galaxy      Start/Stop Galaxy.
+# Init file for Galaxy (http://galaxyproject.org/)
+#   Suitable for use on Fedora and derivatives (RedHat Enterprise Linux, Scientific Linux, CentOS)
 #
-# chkconfig: - 99 99
-# description: Galaxy is a web frontend to a lot of genomics tools.
+# Contributed by Brad Chapman
 #
-# processname: galaxy
-#
-# By: Jean-Baptiste Denis - jbdenis@pasteur.fr
-# It is a base to be sourced (see galaxy-pf* scripts)
-#
-# Based on freshclam init by:
-# (c) 2004/05/17 Petr@Kristof.CZ under GNU GPL 2.0+
+# chkconfig: 2345 98 20
+# description: Galaxy http://galaxyproject.org/
 
-# Source function library
+#--- config
 
-. /etc/init.d/functions
+SERVICE_NAME="galaxy"
+RUN_AS="galaxypa"
+RUN_IN="/data/galaxypa/galaxy"
 
-RETVAL=0
-GUSER="galaxypa"
-GALAXY_HOME="/home/galaxypa"
-
-if [ -z "$GALAXY_HOME" ] ; then
-        echo "You must define GALAXY_HOME."
-        exit 1
-fi
-
-if [ -z "$GUSER" ] ; then
-        echo "You must define GUSER."
-        exit 1
-fi
-
-GALAXY_DIR="$GALAXY_HOME/galaxy"
-GALAXY_LOGS="$GALAXY_HOME/logs"
-PIDFILE="/var/run/galaxy/paster-pasteur-reporting-$GUSER.pid"
-OPTS="-E ./scripts/paster.py serve --log-file $GALAXY_LOGS/galaxy-pasteur-reporting.log config/reports_wsgi.ini --daemon --pid-file=$PIDFILE"
-PYTHON=python
+#--- main actions
 
 start() {
-    echo -n $"Starting galaxy reporting: "
-    # Start me up!
-    daemon --user $GUSER "source ~/.profile && cd $GALAXY_DIR && $PYTHON $OPTS"
-    echo
+        echo "Starting $SERVICE_NAME... "
+        cmd="cd $RUN_IN && sh run_reports.sh --daemon"
+        case "$(id -un)" in
+                $RUN_AS)
+                        eval "$cmd"
+                        ;;
+                root)
+                        su - $RUN_AS -c "$cmd"
+                        ;;
+                *)
+                        echo "*** ERROR *** must be $RUN_AS or root in order to control this service" >&2
+                        exit 1
+        esac
+        echo "...done."
 }
 
 stop() {
-    echo -n $"Stopping galaxy reporting: "
-    killproc -p $PIDFILE
-    echo
+        echo -n "Stopping $SERVICE_NAME... "
+
+        cmd="cd $RUN_IN && sh run_reports.sh --stop-daemon"
+
+        case "$(id -un)" in
+                $RUN_AS)
+                        eval "$cmd"
+                        ;;
+                root)
+                        su - $RUN_AS -c "$cmd"
+                        ;;
+                *)
+                        echo "*** ERROR *** must be $RUN_AS or root in order to control this service" >&2
+                        exit 1
+        esac
+
+        echo "done."
 }
 
-restart() {
-      stop
-    start
+status() {
+        echo -n "$SERVICE_NAME status: "
+
+        while read pid; do
+                if [ "$(readlink -m /proc/$pid/cwd)" = "$(readlink -m $RUN_IN)" ]; then
+                        echo "started"
+                        return 0
+                fi
+        done < <(ps ax -o 'pid cmd' | grep -P '^\s*\d+ python ./scripts/paster.py serve' | awk '{print $1}')
+        echo "stopped"
+        return 3
 }
 
-reload() {
-    stop
-    start
+notsupported() {
+        echo "*** ERROR*** $SERVICE_NAME: operation [$1] not supported"
 }
+
+usage() {
+        echo "Usage: $SERVICE_NAME start|stop|restart|status"
+}
+
+
+#---
 
 case "$1" in
-  start)
-      start
-    ;;
-  stop)
-      stop
-    ;;
-  restart)
-      restart
-    ;;
-  condrestart)
-      [ -f $PIDFILE ] && restart || :
-    ;;
-  reload)
-    reload
-    ;;
-  *)
-    echo $"Usage: $0 {start|stop|restart|condrestart|reload}"
-    exit 1
+        start)
+                start "$@"
+                ;;
+        stop)
+                stop
+                ;;
+        restart|reload)
+                stop
+                start
+                ;;
+        status)
+                set +e
+                status
+                exit $?
+                ;;
+        '')
+                usage >&2
+                exit 1
+                ;;
+        *)
+                notsupported "$1" >&2
+                usage >&2
+                exit 1
+                ;;
 esac
-
-exit $?
-
-
